const { Resend } = require("resend");

const resend = new Resend(process.env.RESEND_API_KEY);

const EMOJI_MAP = {
    smiley: '😊 Happy',
    frowny: '😔 Bored',
    surprised: '😲 Surprised',
    confused: '😕 Confused'
};

const generateReportHTML = (activity, stats, messages) => {
    const total = stats.smiley + stats.frowny + stats.surprised + stats.confused;
    
    return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #6366f1;">Activity Report: ${activity.title}</h1>
        <p style="color: #64748b;">Access Code: ${activity.access_code}</p>
        
        <h2 style="color: #1e293b;">📊 Feedback Summary</h2>
        <table style="width: 100%; border-collapse: collapse;">
            <tr style="background: #f1f5f9;">
                <td style="padding: 10px;">😊 Happy</td>
                <td style="padding: 10px; text-align: right; font-weight: bold;">${stats.smiley}</td>
            </tr>
            <tr>
                <td style="padding: 10px;">😔 Bored</td>
                <td style="padding: 10px; text-align: right; font-weight: bold;">${stats.frowny}</td>
            </tr>
            <tr style="background: #f1f5f9;">
                <td style="padding: 10px;">😲 Surprised</td>
                <td style="padding: 10px; text-align: right; font-weight: bold;">${stats.surprised}</td>
            </tr>
            <tr>
                <td style="padding: 10px;">😕 Confused</td>
                <td style="padding: 10px; text-align: right; font-weight: bold;">${stats.confused}</td>
            </tr>
            <tr style="background: #6366f1; color: white;">
                <td style="padding: 10px; font-weight: bold;">Total</td>
                <td style="padding: 10px; text-align: right; font-weight: bold;">${total}</td>
            </tr>
        </table>
        
        <h2 style="color: #1e293b; margin-top: 30px;">💬 Messages (${messages.length})</h2>
        ${messages.length === 0 ? '<p style="color: #94a3b8;">No messages received</p>' : 
            messages.map(m => `
                <div style="background: #f8fafc; padding: 10px; margin: 5px 0; border-radius: 8px;">
                    <p style="margin: 0;">${m.text}</p>
                    <small style="color: #94a3b8;">${new Date(m.createdAt).toLocaleString()}</small>
                </div>
            `).join('')
        }
        
        <hr style="margin: 30px 0; border: none; border-top: 1px solid #e2e8f0;">
        <p style="color: #94a3b8; font-size: 12px;">
            Generated by ClassPulse • ${new Date().toLocaleString()}
        </p>
    </div>
    `;
};

const sendActivityReport = async (teacherEmail, teacherName, activity, stats, messages) => {
    try {
        const { data, error } = await resend.emails.send({
            from: process.env.EMAIL_FROM,
            to: teacherEmail,
            subject: `📊 Activity Report for ${activity.title}`,
            html: generateReportHTML(activity, stats, messages)
        });

        if (error) {
            console.error('Error sending email:', error);
            return { success: false, error };
        }

        console.log('Email sent successfully:', data);
        return { success: true, id: data.id };
    } catch (err) {
        console.error('Unexpected error sending email:', err);
        return { success: false, error: err };
    }
};

module.exports = { sendActivityReport };